#!perl -w
#
#
# Grab all the values from your Amazon Wish list
# and then print it out 
# 
package amazonwish;

use LWP::UserAgent;
use Getopt::Long;
use WWW::Amazon::Wishlist qw(get_list COM UK);

# --- Configurable variables -----
my $debug_level 	||= 1;

my $uk     		= 0;
my $suffix 		= 'com';
my $match  		= '\$';
my $symbol 		= '$';
my $force  		= 1;
my $save   		= 0;
my $help   		= 0;
my $verbose 		= 1;
my $wishlist_id 	= ""; # put in your amazon
wish list id
my $amazon_url		= "http://www.amazon.com/exec/obidos/ASIN/";
my $associateID		= ""; # put in your
associate id
my $total 		= 0;
my $refnosim		= "/ref=nosim/";


# defined where the resource file is 
my $res  = "$ENV{HOME}/.amazon_wish";

my $package = "amazonwish";

sub debug {
    my ($level, @msg) = @_;

    if ($debug_level >= $level) {
	print STDERR "$package debug $level: @msg\n";
    }
}

sub getwishlist {

# check to see we're valid
die "You haven't defined an id\n" unless (defined $wishlist_id);

# if it's a uk version update the variables
if ($uk)
{
	$suffix = "co.uk";
	$match  = "&pound;";
	$symbol = "£";

		
} 

foreach my $bookref (get_list ($wishlist_id,  $uk))
{
        my %book = %{$bookref};
        debug(1, $book{'title'} . $book{'author'} . $book{'type'} . $book{'asin'});
        $total += $book{'price'} unless (!defined $book{'price'} || $book{'price'} =~ /unavailable/i);
	$amazonwish .= "<A HREF=\"$amazon_url$book{'asin'}$refnosim$associateID\" CLASS=\"Wishitem\">". $book{'title'}. $book{'type'} . "</A><BR>";

} 

#print "------------------------\n" if ($verbose);


# dump
#print sprintf("%s%.2f\n", $symbol, $total);

}

sub start {

debug(1, "Start scraping");
getwishlist;
}
1;

__END__

=head1 NAME

Blosxom Plug-in: amazonwish

=head1 SYNOPSIS

Purpose: Gets your Amazon wishlist.

Uses CSS class


Description

Retrieves your Amazon wishlist.

Configuration

Get a Amazon ID

my $id = "";

$debug_level ||= 1;



Set debuglevel to 0 when the plugin works OK.

Additional Bits Required 

Todo list


=head1 VERSION

2.0

Version number coincides with the version of Blosxom with which the 
current version was first bundled.

=head1 AUTHOR

Peter Florijn  <tooh@tooh.myweb.nl>, http://tooh.myweb.nl/

=head1 SEE ALSO

Blosxom Home/Docs/Licensing: http://www.raelity.org/apps/blosxom/

Blosxom Plugin Docs: http://www.raelity.org/apps/blosxom/plugin.shtml

=head1 BUGS

Address bug reports and comments to the Blosxom mailing list 
[http://www.yahoogroups.com/group/blosxom].

=head1 LICENSE

This Blosxom Plug-in
Copyright 2003, Peter Florijn 

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
